error: catching polymorphic type ‘class bustub::TransactionAbortException’ by value [-Werror=catch-value=]
(cherry picked from commit 67366df48ea6674cdecfaaad4db449a479e4984a)