index_scan_executor.cpp:35:79: error: 'this' argument to member function 'GetInfo' has type 'const bustub::TransactionAbortException', but function is not marked const
(cherry picked from commit f66381ef2bec4975e81054a7b06453913e683dd6)